// src/components/TriangulationPreview.js
import React from 'react';
import styled from 'styled-components';
// Import the JSON data generated by our script
import moneyTrailData from '../data/moneyTrail.json';

// ========== STYLED COMPONENTS ==========
const TriangulationContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 2rem;
  margin: 3rem 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
`;

const Column = styled.div`
  border: 1px solid #e1e4e8;
  border-radius: 12px;
  padding: 1.5rem;
  background: #ffffff;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
  transition: transform 0.2s ease, box-shadow 0.2s ease;

  &:hover {
    transform: translateY(-4px);
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.1);
  }
`;

const ColumnHeader = styled.h3`
  margin-top: 0;
  color: #1a1a1a;
  border-bottom: 2px solid #4a6fa5;
  padding-bottom: 0.75rem;
  font-size: 1.4rem;
`;

const ColumnSubtitle = styled.p`
  color: #666;
  font-size: 0.95rem;
  margin-bottom: 1.25rem;
  font-style: italic;
`;

const DataItem = styled.div`
  padding: 0.85rem;
  border-bottom: 1px solid #f0f0f0;
  font-size: 0.95rem;
  line-height: 1.5;
  color: #333;

  &:last-child {
    border-bottom: none;
  }

  strong {
    color: #2c3e50;
    display: block;
    margin-bottom: 0.25rem;
  }

  &:hover {
    background-color: #f8fafc;
  }
`;

const Timestamp = styled.div`
  font-size: 0.85rem;
  color: #7b8a8b;
  text-align: center;
  margin-top: 1.5rem;
  padding-top: 1rem;
  border-top: 1px dashed #eee;
`;

const SectionTitle = styled.h2`
  color: #2c3e50;
  text-align: center;
  margin-bottom: 2rem;
  font-size: 2rem;
  position: relative;
  
  &:after {
    content: '';
    display: block;
    width: 80px;
    height: 4px;
    background: #4a6fa5;
    margin: 0.5rem auto;
    border-radius: 2px;
  }
`;
// ========== END STYLED COMPONENTS ==========

const TriangulationPreview = () => {
  // Use the fetched data
  const { source, fetched_at, results } = moneyTrailData;

  return (
    <section style={{ padding: '2rem 1rem', maxWidth: '1200px', margin: '0 auto' }}>
      <SectionTitle>Triangulation Engine</SectionTitle>
      
      <TriangulationContainer>
        {/* COLUMN 1: POWER/MONEY TRAIL */}
        <Column>
          <ColumnHeader>💰 Power / Money Trail</ColumnHeader>
          <ColumnSubtitle>Live Federal Campaign Data from FEC</ColumnSubtitle>
          {results && results.length > 0 ? (
            results.map((item, index) => (
              <DataItem key={index}>
                <strong>{item.name || 'Unknown Candidate'}</strong>
                <div>Party: {item.party || 'N/A'}</div>
                <div>Office: {item.office || 'N/A'}</div>
                <div>State: {item.state || 'N/A'}</div>
                <div>ID: <code style={{ fontSize: '0.8rem' }}>{item.candidate_id || 'N/A'}</code></div>
              </DataItem>
            ))
          ) : (
            <DataItem>No data available. The FEC API may be unavailable.</DataItem>
          )}
        </Column>

        {/* COLUMN 2: OFFICIAL NARRATIVE */}
        <Column>
          <ColumnHeader>📢 Official Narrative</ColumnHeader>
          <ColumnSubtitle>Rhetoric, Justifications, Promises</ColumnSubtitle>
          <DataItem>
            <strong>Legislation: "For the People Act"</strong>
            Campaign finance reform bill introduced to increase transparency
          </DataItem>
          <DataItem>
            <strong>Speech: "Restoring Democratic Faith"</strong>
            "We must rebuild trust in our institutions through accountability."
          </DataItem>
          <DataItem>
            <strong>Press Release: Transparency Measures</strong>
            New initiatives announced to track political spending
          </DataItem>
          <DataItem style={{ color: '#4a6fa5', fontStyle: 'italic', backgroundColor: '#f0f7ff', padding: '0.75rem', borderRadius: '6px' }}>
            <strong>Next Integration:</strong> Congress.gov API for live legislative tracking
          </DataItem>
        </Column>

        {/* COLUMN 3: GROUND TRUTH */}
        <Column>
          <ColumnHeader>📈 Ground Truth</ColumnHeader>
          <ColumnSubtitle>Measurable Outcomes & Impacts</ColumnSubtitle>
          <DataItem>
            <strong>Voter Turnout (2024)</strong>
            65.4% (National Average) - Source: U.S. Elections Project
          </DataItem>
          <DataItem>
            <strong>Bills Passed vs. Introduced</strong>
            42/150 (28%) in current session - Source: GovTrack
          </DataItem>
          <DataItem>
            <strong>Public Trust in Government</strong>
            42/100 index score (Gallup, 2024)
          </DataItem>
          <DataItem style={{ color: '#4a6fa5', fontStyle: 'italic', backgroundColor: '#f0f7ff', padding: '0.75rem', borderRadius: '6px' }}>
            <strong>Next Integration:</strong> World Bank & OECD governance indicators
          </DataItem>
        </Column>
      </TriangulationContainer>

      <Timestamp>
        Data Source: <strong>{source}</strong> | 
        Last Updated: {new Date(fetched_at).toLocaleString()} | 
        M.E.G.A. Project v1.0 · Triangulation Engine Active
      </Timestamp>
    </section>
  );
};

export default TriangulationPreview;